<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-F72VL5U5" ignored="1" name="TestOnChrome(failed)" tests="2" failures="2" timestamp="2020-05-01T12:18:24 EDT" time="0.047" errors="0">
  <testcase name="testF2" time="0.015" classname="test.testCases.retryFailedDemo">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at test.testCases.retryFailedDemo.testF2(retryFailedDemo.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testF2 -->
  <testcase name="testF3" time="0.003" classname="test.testCases.retryFailedDemo">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at test.testCases.retryFailedDemo.testF3(retryFailedDemo.java:26)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testF3 -->
  <testcase name="testF1" time="0.0" classname="test.testCases.retryFailedDemo">
    <ignored/>
  </testcase> <!-- testF1 -->
</testsuite> <!-- TestOnChrome(failed) -->
